import { FormEvent, useMemo, useState } from "react";
import { Link, NavLink, Navigate, Outlet } from "react-router-dom";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { toast } from "sonner";
import { supabase } from "@/integrations/supabase/client";
import { useAuth } from "@/hooks/useAuth";
import { AppRole, dashboardNav, hasAny, recordAudit, roleLabels } from "@/lib/frost";
import { AccessDenied, EmptyState, FrostCard, PageHeader, StatusBadge } from "./Ui";

type R = Record<string, any>;
const table = (name: string) => supabase.from(name as any);
function useRows(name: string, order = "updated_at") { return useQuery({ queryKey: ["dash", name], queryFn: async () => (await table(name).select("*").order(order, { ascending: false })).data as R[] || [] }); }
function can(roles: AppRole[], allowed: AppRole[]) { return hasAny(roles, allowed); }

export function DashboardLayout() {
  const { user, roles, loading } = useAuth();
  if (loading) return <section className="container py-20"><div className="frost-card h-40 animate-pulse rounded-lg" /></section>;
  if (!user) return <Navigate to="/login" replace />;
  if (!roles.some(r => r !== "viewer")) return <AccessDenied />;
  const linkClass = ({ isActive }: { isActive:boolean }) => `rounded-md px-3 py-2 text-sm font-bold ${isActive ? "bg-primary/15 text-primary" : "text-muted-foreground hover:bg-secondary/60 hover:text-foreground"}`;
  return <div className="container grid gap-6 py-8 lg:grid-cols-[260px_1fr]"><aside className="frost-card h-fit rounded-lg p-3"><div className="mb-3 rounded-md border border-border bg-secondary/35 p-3"><p className="text-xs text-muted-foreground">Role badge</p><p className="font-command font-bold text-primary">{roles.map(r=>roleLabels[r]).join(", ")}</p></div><nav className="grid gap-1">{dashboardNav.map(([href,label]) => <NavLink key={href} to={href} className={linkClass}>{label}</NavLink>)}</nav></aside><Outlet /></div>;
}

export function DashboardHome() {
  const { data: alliances=[] } = useRows("alliances"); const { data: events=[] } = useRows("events"); const { data: apps=[] } = useRows("transfer_applications", "created_at"); const { data: anns=[] } = useRows("announcements"); const { data: audit=[] } = useRows("audit_logs", "created_at");
  const cards = [["Total alliances", alliances.length], ["Upcoming events", events.length], ["Pending applications", apps.filter(a=>["New","Reviewing"].includes(a.status)).length], ["Latest announcements", anns.length], ["Recent audit activity", audit.length], ["Transfer status", "Open"]];
  return <section><h1 className="font-command text-4xl font-black">Dashboard Overview</h1><div className="mt-6 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{cards.map(([k,v])=><FrostCard key={k as string}><p className="text-muted-foreground">{k}</p><p className="mt-2 font-command text-3xl font-bold text-primary">{v}</p></FrostCard>)}</div></section>;
}

function TextEditor({ name, fields, allowed, title, order = "updated_at" }: { name:string; fields:string[]; allowed:AppRole[]; title:string; order?:string }) {
  const { roles } = useAuth(); const qc = useQueryClient(); const editable = can(roles, allowed); const { data=[] } = useRows(name, order); const [editing, setEditing] = useState<R|null>(null);
  const save = useMutation({ mutationFn: async (row:R) => { const payload = { ...row, updated_by: (await supabase.auth.getUser()).data.user?.id }; const { error } = row.id ? await table(name).update(payload as any).eq("id", row.id) : await table(name).insert(payload as any); if (error) throw error; await recordAudit(row.id ? "update" : "create", name, row.id, editing, payload, roles[0]); }, onSuccess: () => { toast.success("Saved changes."); setEditing(null); qc.invalidateQueries({ queryKey: ["dash", name] }); }, onError: (e:any)=>toast.error(e.message) });
  const remove = async (id:string) => { if (!confirm("Delete this item?")) return; const { error } = await table(name).delete().eq("id", id); error ? toast.error(error.message) : toast.success("Deleted."); qc.invalidateQueries({ queryKey:["dash", name] }); };
  return <section><div className="flex flex-wrap items-center justify-between gap-3"><h1 className="font-command text-4xl font-black">{title}</h1>{editable && <button className="gold-button" onClick={()=>setEditing({})}>Add</button>}</div>{!editable && <p className="mt-3 text-warning">Viewer mode: you do not have edit permission for this manager.</p>}<div className="mt-6 grid gap-4">{data.length ? data.map(row=><FrostCard key={row.id}><div className="flex flex-wrap justify-between gap-3"><div><h2 className="font-command text-xl font-bold">{row.title || row.name || row.current_governor || row.in_game_name}</h2><p className="text-sm text-muted-foreground">Last updated {new Date(row.updated_at || row.created_at).toLocaleString()}</p></div><div className="flex gap-2"><StatusBadge status={row.status || row.recruiting_status || row.category}/>{editable && <button className="ghost-button" onClick={()=>setEditing(row)}>Edit</button>}{editable && <button className="ghost-button" onClick={()=>remove(row.id)}>Delete</button>}</div></div><pre className="mt-3 whitespace-pre-wrap text-sm text-muted-foreground">{fields.map(f=>`${f.replace(/_/g," ")}: ${typeof row[f] === "object" ? JSON.stringify(row[f]) : row[f] || ""}`).join("\n")}</pre></FrostCard>) : <EmptyState title="No records" text="This command table is ready for updates." />}</div>{editing && <div className="fixed inset-0 z-50 grid place-items-center bg-background/80 p-4 backdrop-blur"><form onSubmit={(e:FormEvent)=>{e.preventDefault(); save.mutate(editing);}} className="frost-card max-h-[90vh] w-full max-w-2xl overflow-auto rounded-lg p-5"><h2 className="font-command text-2xl font-bold">Edit {title}</h2><div className="mt-4 grid gap-3">{fields.map(f => f.includes("content") || f.includes("description") || f.includes("message") || f.includes("requirements") || f.includes("instructions") || f.includes("notes") || f.includes("schedule") || f.includes("rotation") ? <textarea key={f} className="field min-h-24" placeholder={f.replace(/_/g," ")} value={typeof editing[f] === "object" ? JSON.stringify(editing[f]) : editing[f] || ""} onChange={e=>setEditing({...editing,[f]: f === "buff_schedule" ? safeJson(e.target.value) : e.target.value})}/> : <input key={f} className="field" placeholder={f.replace(/_/g," ")} value={editing[f] || ""} onChange={e=>setEditing({...editing,[f]:e.target.value})}/>)}</div><div className="mt-5 flex justify-end gap-3"><button type="button" className="ghost-button" onClick={()=>setEditing(null)}>Cancel</button><button className="gold-button" disabled={save.isPending}>Save changes</button></div></form></div>}</section>;
}
function safeJson(v:string){ try { return JSON.parse(v); } catch { return v; } }

export const EventsManager = () => <TextEditor name="events" title="Events Manager" allowed={["owner","event_manager"]} order="created_at" fields={["name","utc_time","local_note","status","description","instructions"]}/>;
export const AllianceManager = () => <TextEditor name="alliances" title="Alliance Manager" allowed={["owner","r5_moderator","r4_moderator"]} order="name" fields={["name","tag","power","main_language","bear_trap_time","foundry_time","crazy_joe_time","canyon_clash_time","alliance_championship_time","recruiting_status","requirements","contact","description"]}/>;
export const RulesManager = () => <TextEditor name="rules_sections" title="Rules Manager" allowed={["owner","governor"]} order="created_at" fields={["title","category","content"]}/>;
export const GovernorManager = () => <TextEditor name="governor_board" title="Governor Board Manager" allowed={["owner","governor"]} fields={["current_governor","minister_rotation","buff_schedule","castle_rotation"]}/>;
export const AnnouncementsManager = () => <TextEditor name="announcements" title="Announcements" allowed={["owner","governor","event_manager","r5_moderator","r4_moderator"]} order="created_at" fields={["title","message","category","visibility","status"]}/>;
export const GuidesManager = () => <TextEditor name="guides" title="Guides Manager" allowed={["owner","governor","event_manager"]} order="title" fields={["title","category","content"]}/>;
export const SvsNotesManager = () => <TextEditor name="svs_notes" title="Private SvS Notes" allowed={["owner","governor","event_manager"]} fields={["title","content","visibility"]}/>;

export function TransferManager() {
  const { roles } = useAuth(); const allowed = can(roles, ["owner","governor","recruiter"]); const { data: apps=[] } = useRows("transfer_applications", "created_at"); const [search,setSearch]=useState(""); const [edit,setEdit]=useState<R|null>(null); const qc=useQueryClient();
  if (!allowed) return <AccessDenied/>;
  const filtered = apps.filter(a=>JSON.stringify(a).toLowerCase().includes(search.toLowerCase()));
  const save = async () => { const { error } = await table("transfer_applications").update({ status: edit?.status, private_notes: edit?.private_notes } as any).eq("id", edit?.id); error ? toast.error(error.message) : toast.success("Application updated."); setEdit(null); qc.invalidateQueries({queryKey:["dash","transfer_applications"]}); };
  return <section><div className="flex flex-wrap justify-between gap-3"><h1 className="font-command text-4xl font-black">Transfer Manager</h1><Link to="/dashboard/transfer-settings" className="ghost-button">Edit transfer page</Link></div><input className="field mt-5 w-full" placeholder="Search applications" value={search} onChange={e=>setSearch(e.target.value)} /><div className="mt-5 grid gap-4">{filtered.map(a=><FrostCard key={a.id}><div className="flex flex-wrap justify-between gap-3"><div><h2 className="font-command text-xl font-bold">{a.in_game_name}</h2><p className="text-muted-foreground">State {a.current_state} · {a.power} · Furnace {a.furnace_level}</p></div><StatusBadge status={a.status}/></div><p className="mt-3 text-muted-foreground">{a.message}</p><button className="gold-button mt-4" onClick={()=>setEdit(a)}>Review</button></FrostCard>)}</div>{edit && <div className="fixed inset-0 z-50 grid place-items-center bg-background/80 p-4"><div className="frost-card w-full max-w-xl rounded-lg p-5"><h2 className="font-command text-2xl font-bold">Review {edit.in_game_name}</h2><select className="field mt-4 w-full" value={edit.status} onChange={e=>setEdit({...edit,status:e.target.value})}>{["New","Reviewing","Accepted","Rejected","Need More Info"].map(s=><option key={s}>{s}</option>)}</select><textarea className="field mt-3 min-h-32 w-full" placeholder="Private recruiter notes" value={edit.private_notes||""} onChange={e=>setEdit({...edit,private_notes:e.target.value})}/><div className="mt-4 flex justify-end gap-3"><button className="ghost-button" onClick={()=>setEdit(null)}>Cancel</button><button className="gold-button" onClick={save}>Save</button></div></div></div>}</section>;
}
export const TransferSettingsManager = () => <TextEditor name="transfer_settings" title="Transfer Settings" allowed={["owner","governor","recruiter"]} fields={["status","power_cap","special_invites","looking_for","requirements","contact_info"]}/>;

export function UsersManager() {
  const { roles } = useAuth(); const allowed = can(roles, ["owner"]); const { data: profiles=[] } = useRows("profiles", "created_at"); const { data: userRoles=[] } = useRows("user_roles", "created_at"); const qc=useQueryClient(); if(!allowed) return <AccessDenied/>;
  const assign = async (user_id:string, role:AppRole) => { const { error } = await table("user_roles").insert({ user_id, role } as any); error ? toast.error(error.message) : toast.success("Role assigned."); qc.invalidateQueries({queryKey:["dash","user_roles"]}); };
  return <section><h1 className="font-command text-4xl font-black">Users & Roles</h1><div className="mt-6 grid gap-4">{profiles.map(p=><FrostCard key={p.id}><div className="flex flex-wrap justify-between gap-3"><div><h2 className="font-command text-xl font-bold">{p.display_name || p.email}</h2><p className="text-muted-foreground">{p.email} · Last login {p.last_login ? new Date(p.last_login).toLocaleString() : "—"}</p><p className="text-primary">{userRoles.filter(r=>r.user_id===p.id).map(r=>roleLabels[r.role as AppRole]).join(", ") || "Viewer"}</p></div><select className="field h-10" onChange={e=>assign(p.id, e.target.value as AppRole)} defaultValue=""><option value="" disabled>Assign role</option>{Object.keys(roleLabels).map(r=><option key={r} value={r}>{roleLabels[r as AppRole]}</option>)}</select></div></FrostCard>)}</div></section>;
}
export function AuditLogPage() { const { roles } = useAuth(); if(!can(roles,["owner"])) return <AccessDenied/>; const { data=[] } = useRows("audit_logs", "created_at"); return <section><h1 className="font-command text-4xl font-black">Audit Log</h1><div className="mt-6 grid gap-3">{data.map(a=><FrostCard key={a.id}><div className="flex flex-wrap justify-between"><b>{a.action} · {a.table_name}</b><span className="text-muted-foreground">{new Date(a.created_at).toLocaleString()}</span></div><pre className="mt-2 overflow-auto text-xs text-muted-foreground">{JSON.stringify(a.new_value, null, 2)}</pre></FrostCard>)}</div></section>; }
